// de1.v

// Generated using ACDS version 24.1 1077

`timescale 1 ps / 1 ps
module de1 (
		input  wire        clk_clk,             //          clk.clk
		input  wire [31:0] hps_0_h2f_gp_gp_in,  // hps_0_h2f_gp.gp_in
		output wire [31:0] hps_0_h2f_gp_gp_out, //             .gp_out
		input  wire        hps_0_uart0_cts,     //  hps_0_uart0.cts
		input  wire        hps_0_uart0_dsr,     //             .dsr
		input  wire        hps_0_uart0_dcd,     //             .dcd
		input  wire        hps_0_uart0_ri,      //             .ri
		output wire        hps_0_uart0_dtr,     //             .dtr
		output wire        hps_0_uart0_rts,     //             .rts
		output wire        hps_0_uart0_out1_n,  //             .out1_n
		output wire        hps_0_uart0_out2_n,  //             .out2_n
		input  wire        hps_0_uart0_rxd,     //             .rxd
		output wire        hps_0_uart0_txd,     //             .txd
		input  wire        hps_0_uart1_cts,     //  hps_0_uart1.cts
		input  wire        hps_0_uart1_dsr,     //             .dsr
		input  wire        hps_0_uart1_dcd,     //             .dcd
		input  wire        hps_0_uart1_ri,      //             .ri
		output wire        hps_0_uart1_dtr,     //             .dtr
		output wire        hps_0_uart1_rts,     //             .rts
		output wire        hps_0_uart1_out1_n,  //             .out1_n
		output wire        hps_0_uart1_out2_n,  //             .out2_n
		input  wire        hps_0_uart1_rxd,     //             .rxd
		output wire        hps_0_uart1_txd,     //             .txd
		output wire [12:0] memory_mem_a,        //       memory.mem_a
		output wire [2:0]  memory_mem_ba,       //             .mem_ba
		output wire        memory_mem_ck,       //             .mem_ck
		output wire        memory_mem_ck_n,     //             .mem_ck_n
		output wire        memory_mem_cke,      //             .mem_cke
		output wire        memory_mem_cs_n,     //             .mem_cs_n
		output wire        memory_mem_ras_n,    //             .mem_ras_n
		output wire        memory_mem_cas_n,    //             .mem_cas_n
		output wire        memory_mem_we_n,     //             .mem_we_n
		output wire        memory_mem_reset_n,  //             .mem_reset_n
		inout  wire [7:0]  memory_mem_dq,       //             .mem_dq
		inout  wire        memory_mem_dqs,      //             .mem_dqs
		inout  wire        memory_mem_dqs_n,    //             .mem_dqs_n
		output wire        memory_mem_odt,      //             .mem_odt
		output wire        memory_mem_dm,       //             .mem_dm
		input  wire        memory_oct_rzqin     //             .oct_rzqin
	);

	wire    hps_0_h2f_cold_reset_reset; // hps_0:h2f_cold_rst_n -> rst_controller:reset_in0
	wire    hps_0_h2f_reset_reset;      // hps_0:h2f_rst_n -> rst_controller:reset_in1

	de1_hps_0 #(
		.F2S_Width (0),
		.S2F_Width (0)
	) hps_0 (
		.h2f_cold_rst_n     (hps_0_h2f_cold_reset_reset), //      h2f_cold_reset.reset_n
		.h2f_mpu_eventi     (),                           //      h2f_mpu_events.eventi
		.h2f_mpu_evento     (),                           //                    .evento
		.h2f_mpu_standbywfe (),                           //                    .standbywfe
		.h2f_mpu_standbywfi (),                           //                    .standbywfi
		.h2f_gp_in          (hps_0_h2f_gp_gp_in),         //              h2f_gp.gp_in
		.h2f_gp_out         (hps_0_h2f_gp_gp_out),        //                    .gp_out
		.uart0_cts          (hps_0_uart0_cts),            //               uart0.cts
		.uart0_dsr          (hps_0_uart0_dsr),            //                    .dsr
		.uart0_dcd          (hps_0_uart0_dcd),            //                    .dcd
		.uart0_ri           (hps_0_uart0_ri),             //                    .ri
		.uart0_dtr          (hps_0_uart0_dtr),            //                    .dtr
		.uart0_rts          (hps_0_uart0_rts),            //                    .rts
		.uart0_out1_n       (hps_0_uart0_out1_n),         //                    .out1_n
		.uart0_out2_n       (hps_0_uart0_out2_n),         //                    .out2_n
		.uart0_rxd          (hps_0_uart0_rxd),            //                    .rxd
		.uart0_txd          (hps_0_uart0_txd),            //                    .txd
		.uart1_cts          (hps_0_uart1_cts),            //               uart1.cts
		.uart1_dsr          (hps_0_uart1_dsr),            //                    .dsr
		.uart1_dcd          (hps_0_uart1_dcd),            //                    .dcd
		.uart1_ri           (hps_0_uart1_ri),             //                    .ri
		.uart1_dtr          (hps_0_uart1_dtr),            //                    .dtr
		.uart1_rts          (hps_0_uart1_rts),            //                    .rts
		.uart1_out1_n       (hps_0_uart1_out1_n),         //                    .out1_n
		.uart1_out2_n       (hps_0_uart1_out2_n),         //                    .out2_n
		.uart1_rxd          (hps_0_uart1_rxd),            //                    .rxd
		.uart1_txd          (hps_0_uart1_txd),            //                    .txd
		.mem_a              (memory_mem_a),               //              memory.mem_a
		.mem_ba             (memory_mem_ba),              //                    .mem_ba
		.mem_ck             (memory_mem_ck),              //                    .mem_ck
		.mem_ck_n           (memory_mem_ck_n),            //                    .mem_ck_n
		.mem_cke            (memory_mem_cke),             //                    .mem_cke
		.mem_cs_n           (memory_mem_cs_n),            //                    .mem_cs_n
		.mem_ras_n          (memory_mem_ras_n),           //                    .mem_ras_n
		.mem_cas_n          (memory_mem_cas_n),           //                    .mem_cas_n
		.mem_we_n           (memory_mem_we_n),            //                    .mem_we_n
		.mem_reset_n        (memory_mem_reset_n),         //                    .mem_reset_n
		.mem_dq             (memory_mem_dq),              //                    .mem_dq
		.mem_dqs            (memory_mem_dqs),             //                    .mem_dqs
		.mem_dqs_n          (memory_mem_dqs_n),           //                    .mem_dqs_n
		.mem_odt            (memory_mem_odt),             //                    .mem_odt
		.mem_dm             (memory_mem_dm),              //                    .mem_dm
		.oct_rzqin          (memory_oct_rzqin),           //                    .oct_rzqin
		.h2f_rst_n          (hps_0_h2f_reset_reset),      //           h2f_reset.reset_n
		.h2f_lw_axi_clk     (clk_clk),                    //    h2f_lw_axi_clock.clk
		.h2f_lw_AWID        (),                           //   h2f_lw_axi_master.awid
		.h2f_lw_AWADDR      (),                           //                    .awaddr
		.h2f_lw_AWLEN       (),                           //                    .awlen
		.h2f_lw_AWSIZE      (),                           //                    .awsize
		.h2f_lw_AWBURST     (),                           //                    .awburst
		.h2f_lw_AWLOCK      (),                           //                    .awlock
		.h2f_lw_AWCACHE     (),                           //                    .awcache
		.h2f_lw_AWPROT      (),                           //                    .awprot
		.h2f_lw_AWVALID     (),                           //                    .awvalid
		.h2f_lw_AWREADY     (),                           //                    .awready
		.h2f_lw_WID         (),                           //                    .wid
		.h2f_lw_WDATA       (),                           //                    .wdata
		.h2f_lw_WSTRB       (),                           //                    .wstrb
		.h2f_lw_WLAST       (),                           //                    .wlast
		.h2f_lw_WVALID      (),                           //                    .wvalid
		.h2f_lw_WREADY      (),                           //                    .wready
		.h2f_lw_BID         (),                           //                    .bid
		.h2f_lw_BRESP       (),                           //                    .bresp
		.h2f_lw_BVALID      (),                           //                    .bvalid
		.h2f_lw_BREADY      (),                           //                    .bready
		.h2f_lw_ARID        (),                           //                    .arid
		.h2f_lw_ARADDR      (),                           //                    .araddr
		.h2f_lw_ARLEN       (),                           //                    .arlen
		.h2f_lw_ARSIZE      (),                           //                    .arsize
		.h2f_lw_ARBURST     (),                           //                    .arburst
		.h2f_lw_ARLOCK      (),                           //                    .arlock
		.h2f_lw_ARCACHE     (),                           //                    .arcache
		.h2f_lw_ARPROT      (),                           //                    .arprot
		.h2f_lw_ARVALID     (),                           //                    .arvalid
		.h2f_lw_ARREADY     (),                           //                    .arready
		.h2f_lw_RID         (),                           //                    .rid
		.h2f_lw_RDATA       (),                           //                    .rdata
		.h2f_lw_RRESP       (),                           //                    .rresp
		.h2f_lw_RLAST       (),                           //                    .rlast
		.h2f_lw_RVALID      (),                           //                    .rvalid
		.h2f_lw_RREADY      (),                           //                    .rready
		.h2f_uart0_irq      (),                           // h2f_uart0_interrupt.irq
		.h2f_uart1_irq      ()                            // h2f_uart1_interrupt.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (2),
		.OUTPUT_RESET_SYNC_EDGES   ("none"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~hps_0_h2f_cold_reset_reset), // reset_in0.reset
		.reset_in1      (~hps_0_h2f_reset_reset),      // reset_in1.reset
		.clk            (),                            //       clk.clk
		.reset_out      (),                            // reset_out.reset
		.reset_req      (),                            // (terminated)
		.reset_req_in0  (1'b0),                        // (terminated)
		.reset_req_in1  (1'b0),                        // (terminated)
		.reset_in2      (1'b0),                        // (terminated)
		.reset_req_in2  (1'b0),                        // (terminated)
		.reset_in3      (1'b0),                        // (terminated)
		.reset_req_in3  (1'b0),                        // (terminated)
		.reset_in4      (1'b0),                        // (terminated)
		.reset_req_in4  (1'b0),                        // (terminated)
		.reset_in5      (1'b0),                        // (terminated)
		.reset_req_in5  (1'b0),                        // (terminated)
		.reset_in6      (1'b0),                        // (terminated)
		.reset_req_in6  (1'b0),                        // (terminated)
		.reset_in7      (1'b0),                        // (terminated)
		.reset_req_in7  (1'b0),                        // (terminated)
		.reset_in8      (1'b0),                        // (terminated)
		.reset_req_in8  (1'b0),                        // (terminated)
		.reset_in9      (1'b0),                        // (terminated)
		.reset_req_in9  (1'b0),                        // (terminated)
		.reset_in10     (1'b0),                        // (terminated)
		.reset_req_in10 (1'b0),                        // (terminated)
		.reset_in11     (1'b0),                        // (terminated)
		.reset_req_in11 (1'b0),                        // (terminated)
		.reset_in12     (1'b0),                        // (terminated)
		.reset_req_in12 (1'b0),                        // (terminated)
		.reset_in13     (1'b0),                        // (terminated)
		.reset_req_in13 (1'b0),                        // (terminated)
		.reset_in14     (1'b0),                        // (terminated)
		.reset_req_in14 (1'b0),                        // (terminated)
		.reset_in15     (1'b0),                        // (terminated)
		.reset_req_in15 (1'b0)                         // (terminated)
	);

endmodule
