#!/usr/bin/env quartus_sh
# Quartus project setup script for BitSys with HPS UART routing
# This script MUST be run AFTER Qsys has generated hps_system.sv
# Usage: quartus_sh -t setup_project_hps.tcl

# ─── Configuration ───────────────────────────────────────────────────────
set PROJECT_NAME     "bitsys_de1"
set DEVICE           "5CSEMA5F31C6"
set FAMILY           "Cyclone V"
set TOP_LEVEL_ENTITY "bitsys_hps_top"
set BAUD_RATE        115200

# ─── Create Project ──────────────────────────────────────────────────────
project_new $PROJECT_NAME -overwrite -family $FAMILY -device $DEVICE

# ─── Add Source Files ────────────────────────────────────────────────────
# Add all RTL source files
set_global_assignment -name SYSTEMVERILOG_FILE ../rtl/bitsys_pkg.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../rtl/bitsys_pe_t1.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../rtl/bitsys_pe_t2.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../rtl/bitsys_mul.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../rtl/bitsys_accu_conv.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../rtl/bitsys_mac.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../rtl/bitsys_clock_gate.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../rtl/bitsys_systolic_array.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../rtl/uart_rx.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../rtl/uart_tx.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../rtl/bitsys_uart_top.sv
set_global_assignment -name SYSTEMVERILOG_FILE ../rtl/bitsys_hps_top.sv

# Add HPS system (generated from Qsys)
# IMPORTANT: hps_system.sv must be generated by Qsys before running this script
set_global_assignment -name SYSTEMVERILOG_FILE hps_system.sv
set_global_assignment -name QIP_FILE hps_system.qip

# ─── Project Settings ────────────────────────────────────────────────────
set_global_assignment -name TOP_LEVEL_ENTITY $TOP_LEVEL_ENTITY
set_global_assignment -name ORIGINAL_QUARTUS_VERSION "24.1STD.0"
set_global_assignment -name PROJECT_CREATION_TIME_DATE "04/22/2026 15:00:00"
set_global_assignment -name LAST_QUARTUS_VERSION "24.1std.0 Lite Edition"

# ─── Compiler Settings ──────────────────────────────────────────────────
set_global_assignment -name EDA_DESIGN_INSTANCE_NAME NA -section_id eda_design_synthesis
set_global_assignment -name EDA_NATIVELINK_SIMULATION_TEST_BENCH tb_bitsys_systolic_array -section_id eda_simulation
set_global_assignment -name EDA_TIME_SCALE "1 ps" -section_id eda_simulation
set_global_assignment -name EDA_OUTPUT_DATA_FORMAT SYSTEMVERILOG -section_id eda_simulation

# Enable synthesis of gated clocks
set_global_assignment -name SYNTH_GATED_CLOCK_CONVERSION OFF

# Parallel compilation
set_global_assignment -name NUM_PARALLEL_PROCESSORS 4

# Optimization
set_global_assignment -name OPTIMIZATION_MODE AGGRESSIVE
set_global_assignment -name REMOVE_DUPLICATE_REGISTERS ON

# ─── Pin Assignments (DE1-SoC) ──────────────────────────────────────────
# System Clock and Reset
set_location_assignment PIN_AF14 -to clk
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to clk
set_location_assignment PIN_AE9 -to rst_n
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to rst_n

# UART Signals (routed through HPS UART to FPGA fabric)
# These pins are HPS-controlled and will be auto-configured by Platform Designer
set_location_assignment PIN_B25 -to uart_rx
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to uart_rx
set_location_assignment PIN_C25 -to uart_tx
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to uart_tx

# IMPORTANT: DO NOT manually assign HPS I/O pins (hps_io[*])
# These are auto-assigned by Quartus based on the HPS configuration

# ─── Save and Close ──────────────────────────────────────────────────────
export_assignments
save_project

puts ""
puts "╔════════════════════════════════════════════════════════════╗"
puts "║  Quartus Project Created Successfully                      ║"
puts "╠════════════════════════════════════════════════════════════╣"
puts "║  Project Name     : $PROJECT_NAME                          ║"
puts "║  Top Level Entity : $TOP_LEVEL_ENTITY                      ║"
puts "║  Device           : $DEVICE                                ║"
puts "║  UART Baud Rate   : $BAUD_RATE                             ║"
puts "╠════════════════════════════════════════════════════════════╣"
puts "║  Next Steps:                                               ║"
puts "║  1. Ensure hps_system.sv is generated from Qsys            ║"
puts "║  2. Run: quartus_map bitsys_de1                            ║"
puts "║  3. Run: quartus_fit bitsys_de1                            ║"
puts "║  4. Run: quartus_asm bitsys_de1                            ║"
puts "║  5. Program FPGA with bitsys_de1.sof                       ║"
puts "╚════════════════════════════════════════════════════════════╝"
puts ""
